Syntax highlight
radish-bdd/radish-bdd.github.io pull request #5
Opened 2017-03-02 18:44 UTC by deeechun

I've added in a source pointing to a link online for the highlighter.js file. If you want, I can download the js file locally and just point to the file in case the site i'm pointing to goes down

2017-03-02 19:35 UTC, timofurrer requested changes
Thanks for the PR! :tada: 

You can actually have a look at how it looks generated by serving the site with jekyll:

```bash
# you might want to run this as root
gem install jekyll bundler
# serve the site
jekyll serve
```

:beers:

2017-03-02 19:35 UTC, timofurrer commented on _includes/js.html
> +    </script>
You have to enable highlightjs in order to make it work. Add the following after including the JS files from the CDN:

```html
<script>hljs.initHighlightingOnLoad();</script>
```

2017-03-02 19:35 UTC, timofurrer commented on _includes/gettingstarted.html
> +                                            # -*- coding: utf-8 -*-
Inside `<code>`-tags the indentation actually matters. That's why this line will be indented in a weird way. 
Also pay attention to leading and trailing new/blank lines.

2017-03-02 19:49 UTC, deeechun commented
Wow you're a life saver. I was wondering how I can check changes online for indentation errors, etc. 

Also, I completely forgot to add in that initialization script after playing around with it for a little bit XD. I will fix the indentation and submit another PR.

2017-03-02 20:14 UTC, timofurrer commented
Looks much better now. Is it possible to remove this gray border around the code blocks?

![image](https://cloud.githubusercontent.com/assets/1008252/23524987/2debc7ae-ff8d-11e6-86c4-64c7d8c79d46.png)

2017-03-02 21:07 UTC, deeechun commented
Does this look alright?
![screenshot from 2017-03-02 13-06-35](https://cloud.githubusercontent.com/assets/12178181/23527026/1f89664c-ff49-11e6-95f0-7fbfcf280e98.png)

2017-03-02 21:08 UTC, deeechun commented
Would this be alright?
![screenshot from 2017-03-02 13-08-02](https://cloud.githubusercontent.com/assets/12178181/23527069/4c6082e0-ff49-11e6-93d3-fc9040ca9d81.png)

2017-03-02 21:13 UTC, timofurrer commented
Yeah, looks better. Can we make a 1px border though? Like before just without the cap? And please increase the width of the steps code block a little so the `given` decorator fits on one line.

If some of those is not possible let me know.

2017-03-02 23:06 UTC, deeechun commented
Sure, changed it. I'll commit now.
![screenshot from 2017-03-02 15-04-37](https://cloud.githubusercontent.com/assets/12178181/23531137/c9b6747e-ff59-11e6-95aa-f1259223e528.png)

2017-03-03 06:30 UTC, timofurrer approved these changes

2017-03-03 06:30 UTC, merged

2017-03-03 06:30 UTC, timofurrer commented
Awesome, thanks! :beers: